name: OrataPayboxBundle

on:
    push:
        branches: ['master', 'refacto']
        paths-ignore:
            - 'README'
            - '.gitignore'
    pull_request: ~
    workflow_dispatch: ~

jobs:
    syntax-php:
        name: Syntax PHP
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Check valid syntax for all php files
              run: |
                touch ./ERRORS
                for PHPFILE in $(find . -type f -name "*.php"); do
                    php -l $PHPFILE > /dev/null || php -l $PHPFILE >> ./ERRORS
                done
                cat ./ERRORS
                if grep -iq "error" ./ERRORS; then
                    exit 1
                fi
    tests:
        name: PHPUnit Tests
        runs-on: ubuntu-latest
        needs: 'syntax-php'
        strategy:
            matrix:
                include:
                    - php: '7.2'
                      symfony: '5.4.*'
                    - php: '7.3'
                      symfony: '5.4.*'
                    - php: '7.4'
                      symfony: '5.4.*'
                    - php: '8.0'
                      symfony: '6.0.*'
                    - php: '8.1'
                      symfony: '6.4.*'
                    - php: '8.2'
                      symfony: '7.0.*'
                    - php: '8.3'
                      symfony: '7.0.*'
            fail-fast: false
        steps:
            # php
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: "${{ matrix.php }}"
                  tools: composer:v2
            - name: Git checkout placeholder-service
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: composer config extra.symfony.require ${{ matrix.symfony }}
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
            - name: PHPUnit
              run: vendor/bin/phpunit
